# Generated by Django 3.2.9 on 2021-11-25 00:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import park_data.models.timestamped


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.CharField(help_text='This ID uniquely identifies a pool through all history', max_length=64, unique=True, verbose_name='Pool ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Name')),
                ('public_url', models.URLField(blank=True, max_length=4096, null=True, verbose_name='Public website')),
                ('source_url', models.URLField(blank=True, max_length=4096, null=True, verbose_name='Data website')),
                ('license', models.TextField(blank=True, null=True, verbose_name='License')),
            ],
            options={
                'verbose_name': 'Pool',
                'verbose_name_plural': 'Pools',
            },
            bases=(park_data.models.timestamped.TimestampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(help_text='This ID uniquely identifies a single parking lot through all history', max_length=64, unique=True, verbose_name='ID of parking lot')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Name')),
                ('address', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Address of parking lot')),
                ('type', models.CharField(blank=True, db_index=True, help_text="Let's see what base types we can crystalize", max_length=64, null=True, verbose_name='Type of lot')),
                ('max_capacity', models.IntegerField(blank=True, db_index=True, help_text='The number of maximum total spaces that have been encountered', null=True, verbose_name='Maximum total spaces')),
                ('has_live_capacity', models.BooleanField(db_index=True, verbose_name='Has live capacity?')),
                ('public_url', models.URLField(blank=True, max_length=4096, null=True, verbose_name='Public website')),
                ('source_url', models.URLField(blank=True, max_length=4096, null=True, verbose_name='Data website')),
                ('geo_point', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326, verbose_name='Geo point')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park_data.parkingpool', verbose_name='Pool')),
            ],
            options={
                'verbose_name': 'Parking lot',
                'verbose_name_plural': 'Parking lots',
            },
            bases=(park_data.models.timestamped.TimestampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ParkingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Datetime of snapshot (UTC)', verbose_name='Timestamp')),
                ('lot_timestamp', models.DateTimeField(blank=True, db_index=True, help_text='Last update of published lot data', null=True, verbose_name='Last update')),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('unknown', 'unknown'), ('nodata', 'nodata'), ('error', 'error')], db_index=True, help_text='Status of parking lot (website)', max_length=16, verbose_name='Status')),
                ('num_free', models.IntegerField(blank=True, db_index=True, help_text='Number of free spaces', null=True, verbose_name='Free')),
                ('capacity', models.IntegerField(blank=True, db_index=True, help_text='Number of total available spaces', null=True, verbose_name='Capacity')),
                ('num_occupied', models.IntegerField(blank=True, db_index=True, help_text='Number of occupied spaces', null=True, verbose_name='Occupied')),
                ('percent_free', models.FloatField(blank=True, db_index=True, help_text='Percentage of free spaces', null=True, verbose_name='Free %')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park_data.parkinglot', verbose_name='Parking lot')),
            ],
            options={
                'verbose_name': 'Parking data',
                'verbose_name_plural': 'Parking data',
                'unique_together': {('timestamp', 'lot')},
            },
        ),
    ]
