# Generated by Django 3.2.9 on 2021-11-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestParkingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Datetime of snapshot (UTC)', verbose_name='Timestamp')),
                ('lot_timestamp', models.DateTimeField(blank=True, db_index=True, help_text='Last update of published lot data', null=True, verbose_name='Last update')),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('unknown', 'unknown'), ('nodata', 'nodata'), ('error', 'error')], db_index=True, help_text='Status of parking lot (website)', max_length=16, verbose_name='Status')),
                ('num_free', models.IntegerField(blank=True, db_index=True, help_text='Number of free spaces', null=True, verbose_name='Free')),
                ('capacity', models.IntegerField(blank=True, db_index=True, help_text='Number of total available spaces', null=True, verbose_name='Capacity')),
                ('num_occupied', models.IntegerField(blank=True, db_index=True, help_text='Number of occupied spaces', null=True, verbose_name='Occupied')),
                ('percent_free', models.FloatField(blank=True, db_index=True, help_text='Percentage of free spaces', null=True, verbose_name='Free %')),
            ],
            options={
                'verbose_name': 'Latest parking data',
                'verbose_name_plural': 'Latest parking data',
            },
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='latest_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='park_data.latestparkingdata', verbose_name='Latest data'),
        ),
    ]
