# Generated by Django 3.2.9 on 2021-11-28 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_data', '0003_add_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow, help_text='Datetime of snapshot (UTC)', verbose_name='Timestamp')),
                ('source', models.CharField(choices=[('module', 'module'), ('pool', 'pool')], db_index=True, max_length=16, verbose_name='Source of error')),
                ('module_name', models.CharField(db_index=True, help_text='Name of the scraper module', max_length=64, verbose_name='Module name')),
                ('pool_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Pool ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Error text')),
                ('stacktrace', models.TextField(blank=True, null=True, verbose_name='Stacktrace')),
            ],
            options={
                'verbose_name': 'Error log',
                'verbose_name_plural': 'Error logs',
            },
        ),
    ]
