# Generated by Django 3.2.9 on 2021-11-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_data', '0004_errorlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingpool',
            old_name='license',
            new_name='attribution_license',
        ),
        migrations.AddField(
            model_name='parkingpool',
            name='attribution_contributor',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contributor'),
        ),
        migrations.AddField(
            model_name='parkingpool',
            name='attribution_url',
            field=models.URLField(blank=True, max_length=4096, null=True, verbose_name='Attribution url'),
        ),
    ]
