# Generated by Django 3.2.9 on 2021-11-27 14:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last update')),
                ('osm_id', models.CharField(db_index=True, help_text='The ID is prefixed with N, W or R (for Node, Way or Relation)', max_length=32, unique=True, verbose_name='OpenStreetMap ID')),
                ('geo_point', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326, verbose_name='Geographic center')),
                ('osm_properties', models.JSONField(blank=True, null=True, verbose_name='Properties from OSM')),
                ('city', models.CharField(blank=True, db_index=True, help_text='Native language name', max_length=64, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, db_index=True, help_text='Native language name', max_length=64, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, db_index=True, help_text='Native language name', max_length=64, null=True, verbose_name='Country')),
                ('country_code', models.CharField(blank=True, db_index=True, help_text='two-letter ISO 3166 lowercase', max_length=2, null=True, verbose_name='Countrycode')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
