version: '3'
services:
  db:
    image: postgis/postgis:16-3.4
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file: .env 
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parkapi2"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["runserver", "0.0.0.0:8000"]
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - RUN_MIGRATION=1
  scraper:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: 
      - pa_scrape
      - scrape
      - -j
      - "100"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
