# Generated by Django 3.2.9 on 2021-11-22 13:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSMLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date of creation')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date of update')),
                ('osm_id', models.CharField(db_index=True, help_text='The ID must be prefixed with N, W or R (for Node, Way or Relation)', max_length=32, unique=True, verbose_name='OpenStreetMap ID')),
                ('osm_place_rank', models.IntegerField(blank=True, db_index=True, help_text='The higher, the smaller', null=True, verbose_name='Place rank')),
                ('osm_feature_type', models.CharField(blank=True, db_index=True, help_text="This is not the 'osm_type', it's simply the 'type'", max_length=32, null=True, verbose_name='Type of object')),
                ('osm_linked_place', models.CharField(blank=True, db_index=True, help_text="Comes from OSM 'feature.extratags.linked_place'", max_length=32, null=True, verbose_name='Type of place')),
                ('osm_properties', models.JSONField(blank=True, null=True, verbose_name='Properties from OSM')),
                ('name', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Name')),
                ('geo_point', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326, verbose_name='Geographic center')),
                ('geo_polygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, db_index=True, null=True, srid=4326, verbose_name='Geographic outline')),
                ('osm_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osm_locations.osmlocation', verbose_name='Administrative parent')),
            ],
            options={
                'verbose_name': 'OSM Location',
                'verbose_name_plural': 'OSM Locations',
            },
        ),
    ]
