name: build & publish Docker image

on:
  push:
    branches:
      # TODO: rename master to main
      - master
      # TODO: remove before merge
      - docker

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: set up Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: log into the GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: lowercase repo name
      id: lower-repo
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ github.repository }}

    - name: set current date as env variable
      id: version
      run: |
        echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
    - name: build and push Docker image
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ steps.lower-repo.outputs.lowercase }}:latest,ghcr.io/${{ steps.lower-repo.outputs.lowercase }}:${{ steps.version.outputs.builddate }}
        platforms: linux/amd64,linux/arm64
        # https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
        cache-from: type=gha
        cache-to: type=gha,mode=max

